# Primeiro definimos uma imagem mais leve do Python
FROM python:3.11-slim

# Precisamos configurar o ambiente para logs em tempo real e evitar arquivos .pyc
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# pacotes do sistem aneecssários
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# copiar e instalar os requirimentos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ..

EXPOSE 8000

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"]