"""migration_v.0.0.4

Revision ID: 352d888ca6e1
Revises: 501aca5395fc
Create Date: 2026-08-06 21:03:24.141460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352d888ca6e1'
down_revision: Union[str, Sequence[str], None] = '501aca5395fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor_aplicado', sa.Float(), nullable=False),
    sa.Column('valor_mercado', sa.Float(), nullable=False),
    sa.Column('ganho_capital', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['perfil_pessoal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_patrimonio_data'), 'historico_patrimonio', ['data'], unique=False)
    op.create_index(op.f('ix_historico_patrimonio_usuario_id'), 'historico_patrimonio', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_patrimonio_usuario_id'), table_name='historico_patrimonio')
    op.drop_index(op.f('ix_historico_patrimonio_data'), table_name='historico_patrimonio')
    op.drop_table('historico_patrimonio')
    # ### end Alembic commands ###
