"""migration_v.0.0.2

Revision ID: c70e773e4c57
Revises: 87f0a5a7eeb8
Create Date: 2026-08-05 22:18:37.021776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c70e773e4c57'
down_revision: Union[str, Sequence[str], None] = '87f0a5a7eeb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotacoes_diarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('preco_fechamento', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cotacao_ativo_data', 'cotacoes_diarias', ['ativo_id', 'data'], unique=True)
    op.create_index(op.f('ix_cotacoes_diarias_ativo_id'), 'cotacoes_diarias', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_cotacoes_diarias_data'), 'cotacoes_diarias', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cotacoes_diarias_data'), table_name='cotacoes_diarias')
    op.drop_index(op.f('ix_cotacoes_diarias_ativo_id'), table_name='cotacoes_diarias')
    op.drop_index('idx_cotacao_ativo_data', table_name='cotacoes_diarias')
    op.drop_table('cotacoes_diarias')
    # ### end Alembic commands ###
